lovers_lock_cadenas:
    resource: "@LoversLockCadenasBundle/Controller/"
    type:     annotation
    prefix:   /

pont:
    path:   /
    defaults:  { _controller: LoversLockPontBundle:Default:index }

admin:
    path:   /admin
    defaults:  { _controller: LoversLockUtilisateurBundle:Default:admin }

utlisateur:
    resource: "@LoversLockUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /utilisateur

#HWIOAuthBundle routes


hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /redirect

facebook_login:
    pattern: /login/check-facebook
    defaults:  { _controller: LoversLockCadenasBundle:Default:index }

